AsmResolver/X86/MultiByteOpCodes.cs
Fixed the problem of decoding movzx ecx, al
It seems the multibytes opcodes are all missing registertoken
=> Fixed the decoding problem of some multibyte opcodes #19

src/AsmResolver.DotNet/AssemblyDefinition.cs, src/AsmResolver.DotNet/ModuleDefinition.cs
Added 3 Write() methods to allow AssemblyDefinition to write the manifest module to a stream.
=> AssemblyDefinition is now able to write the ManifestModule to a stream. ModuleDefinition now has .ToPEImage()

src/AsmResolver.DotNet/Code/Cil/CilMethodBody.cs
As ECMA states, "Tiny headers" use 6-bit length encoding, therefore the length should be not longer than 63. Previous code would categorize a body with a length of 64 as "Tiny", while it is actually a "Fat" format. This would lead to an ArgumentException on writing.
=> Fixed IsFat property in CilMethodBody.

README.md
README mentioned that AsmResolver targets .NET Framework 4.0, but it has been targeting .NET Standard exclusively since cba273df6e8deeda0bb72e23bab99352f0864056. This PR removes it, and mentions that the .NET Core SDK is required.
=> Update outdated framework info in README

src/AsmResolver.DotNet/Cloning/MemberCloner.cs, src/AsmResolver.DotNet/GenericParameter.cs, src/AsmResolver.DotNet/Serialized/SerializedGenericParameter.cs
Before this change, if you add more than 1 GenericParameter to a method definition, all of them would be written with the same number.
=> Fixed the issue with writing GenericParams

test/TestBinaries/DotNet/HelloWorld/HelloWorld.csproj, test/TestBinaries/DotNet/TheAnswer/TheAnswer.csproj
Due to new visual studio installer not having .net 4.0 install option, i bumped test app versions to later framework version.
=> Bump test app framework version

src/AsmResolver.DotNet/Signatures/GenericContext.cs, test/AsmResolver.DotNet.Tests/Signatures/GenericContextTest.cs
In case when we want to partially replace generic values (only Vars, or only MVars) on methods that contains both, we don't want to throw error when second provider is missing
=> Fix: Throw on generic context GetTypeArgument + Add: GenericContext From  methods

src/AsmResolver.PE/DotNet/Cil/CilCode.cs, src/AsmResolver.PE/DotNet/Cil/CilOpCodes.cs
This pull request adds documentation for the CilOpCodes class.
The lines for this were pulled from https://en.wikipedia.org/wiki/List_of_CIL_instructions
The only ones I couldn't find information for was the Prefix OpCodes.
=> Feature/ Add Documentation for CilOpCodes

src/AsmResolver.DotNet/AssemblyDefinition.cs
Previously, `AssemblyDefinition.Write` would throw a `DirectoryNotFoundException` if provided a relative path without any directories, such as `output.dll`. This pull request make it use the full path instead, avoiding this issue.
=> Fix/ AssemblyDefinition Write to relative path

src/AsmResolver.DotNet/AssemblyDefinition.cs, src/AsmResolver.DotNet/DotNetFrameworkAssemblyResolver.cs, test/AsmResolver.DotNet.Tests/AssemblyResolverTest.cs
=> Feature/GAC Directory Priorities

src/AsmResolver.DotNet/Builder/Discovery/MemberDiscoverer.cs, src/AsmResolver.DotNet/FieldDefinition.cs, src/AsmResolver.DotNet/Signatures/FieldSignature.cs, test/AsmResolver.DotNet.Tests/Builder/TokenMappingTest.cs, test/AsmResolver.DotNet.Tests/Builder/TokenPreservation/FieldTokenPreservationTest.cs, test/AsmResolver.DotNet.Tests/FieldDefinitionTest.cs, test/AsmResolver.DotNet.Tests/MetadataResolverTest.cs, test/AsmResolver.DotNet.Tests/ReferenceImporterTest.cs, test/AsmResolver.DotNet.Tests/Signatures/GenericContextTest.cs, test/AsmResolver.DotNet.Tests/TokenAllocatorTest.cs
The HasThis bit is ignored by the CLR. It is therefore not a good representation of whether a field is static or not, and it should therefore not be promoted to be used either.
=> Deprecate FieldSignature.CreateXXX Factory methods

src/AsmResolver.DotNet/Code/MethodBody.cs, src/AsmResolver.DotNet/Code/UnresolvedMethodBody.cs, src/AsmResolver.DotNet/Serialized/DefaultMethodBodyReader.cs, test/AsmResolver.DotNet.Tests/Code/Native/NativeMethodBodyTest.cs
- Add `MethodBody.Address`, containing the reference within the input file if the method came from a serialized module.
- Fixes exceptions being thrown upon trying to read native method bodies from serialized modules.
- Replaces any unrecognized method body type with an instance of `UnresolvedMethodBody`.
=> Unresolved method bodies

src/AsmResolver.DotNet/Builder/DotNetDirectoryBuffer.TokenProvider.cs, src/AsmResolver.DotNet/Builder/DotNetDirectoryFactory.cs, src/AsmResolver.DotNet/Builder/Metadata/Tables/DistinctMetadataTableBuffer.cs, src/AsmResolver.DotNet/Builder/Metadata/Tables/TablesStreamBuffer.cs, test/AsmResolver.DotNet.Tests/Builder/TokenPreservation/AssemblyRefTokenPreservationTest.cs, test/AsmResolver.DotNet.Tests/Builder/TokenPreservation/MemberRefTokenPreservationTest.cs, test/AsmResolver.DotNet.Tests/Builder/TokenPreservation/TokenPreservationTestBase.cs, test/AsmResolver.DotNet.Tests/Builder/TokenPreservation/TypeRefTokenPreservationTest.cs, test/AsmResolver.DotNet.Tests/TokenAllocatorTest.cs
Fixes a bug related to token preservation of metadata members within `DistinctMetadataTableBuffer`s. 
Closes #252
=> Preserve duplicate metadata members when required

docs/dotnet/managed-method-bodies.rst, src/AsmResolver.PE/DotNet/Cil/CilInstruction.cs, test/AsmResolver.PE.Tests/DotNet/Cil/CilInstructionTest.cs
Adds `ReplaceWith`  and `ReplaceWithNop` utility functions to `CilInstruction`.
=> CilInstruction.ReplaceWith

src/AsmResolver.DotNet/Code/Cil/StackImbalanceException.cs, src/AsmResolver.DotNet/Memory/TypeMemoryLayoutDetector.cs, src/AsmResolver.DotNet/Signatures/MemberSignature.cs, src/AsmResolver.DotNet/Signatures/MethodSignature.cs, src/AsmResolver.DotNet/Signatures/PropertySignature.cs, src/AsmResolver.DotNet/Signatures/Security/SecurityAttribute.cs
This pull request replaces a few uses of `string.Format` with string interpolation.
I also did some performance testing on the potential benefits of having .NET 6 targets.
```cs
using System;
using System.Diagnostics;
using System.IO;
using AsmResolver.DotNet;
namespace SpeedTestNet6
{
internal class Program
{
private const string OutputPath = "output.dll";
private const int NumTests = 100;
private static Stopwatch stopwatch = new Stopwatch();
static void Main(string[] args)
{
long[] results = RunTests();
PrintStatistics(results);
Console.ReadLine();
}
private static void PrintStatistics(long[] data)
{
Console.WriteLine();
double mean = Average(data);
Console.WriteLine($"Mean: {mean}");
double stddev = StandardDeviation(data, mean);
Console.WriteLine($"StdDev: {stddev}");
}
private static …
```
=> Feature/Minor Performance Improvement

src/AsmResolver.DotNet/DefaultMetadataResolver.cs
As discussed, closes #269. Some of the unit tests aren't passing on my local machine (41 of the 44 under Builder/TokenPreservation) but they don't pass on master either (but they seem to work on AppVeyor?) so I'm assuming I haven't broken anything. The error is 
`
System.BadImageFormatException: Input PE image does not contain a .NET metadata directory.
`.
=> Use ConcurrentDictionary as backing cache for DefaultMetadataResolver

src/AsmResolver.DotNet/ReferenceImporter.cs, test/AsmResolver.DotNet.Tests/ReferenceImporterTest.cs
Ensures both top level as well as nested `TypeDefinition`s are imported properly.
Closes #273
=> Import TypeDefinition scopes

src/AsmResolver.DotNet/Builder/Metadata/Blob/BlobStreamBuffer.cs, src/AsmResolver.DotNet/Builder/Metadata/Guid/GuidStreamBuffer.cs, src/AsmResolver.DotNet/Builder/Metadata/UserStrings/UserStringsStreamBuffer.cs, src/AsmResolver.DotNet/Builder/Resources/DotNetResourcesDirectoryBuffer.cs, src/AsmResolver.DotNet/Collections/ParameterCollection.cs, src/AsmResolver.DotNet/DefaultMetadataResolver.cs, src/AsmResolver.PE.File/SerializedPEFile.cs, src/AsmResolver.PE.Win32Resources/Icon/IconResource.cs, src/AsmResolver.PE.Win32Resources/Version/StringTable.cs, src/AsmResolver.PE.Win32Resources/Version/VersionInfoResource.cs, src/AsmResolver.PE/DotNet/Metadata/Tables/TablesStream.cs
Closes #271 
A note on the change from:
```cs
_typeCache.Remove(type);
```
To:
```cs
_typeCache.TryRemove(type, out _);
```
The runtime uses this behavior too:
https://github.com/dotnet/runtime/blob/3ae87395f638a533f37b8e3385f6d3f199a72f4f/src/libraries/System.Collections.Concurrent/src/System/Collections/Concurrent/ConcurrentDictionary.cs#L1472
=> Use actual types for private readonly fields

src/AsmResolver.DotNet/Cloning/CloneContextAwareReferenceImporter.cs
=> [Feature]: Redirect System.Object base type when member cloning

src/AsmResolver.DotNet/Cloning/CloneContextAwareReferenceImporter.cs, src/AsmResolver.DotNet/Cloning/MemberCloneContext.cs, src/AsmResolver.DotNet/Cloning/MemberCloner.cs
A draft pull request for addressing #93
One of the major design decisions I made was to require that any custom importers inherit from `CloneContextAwareReferenceImporter` instead of `ReferenceImporter` or a hypothetical `IReferenceImporter` interface. I felt that this was the cleanest way to maintain correct references between cloned members.
=> [Feature]: Custom ReferenceImporter in MemberCloner

src/AsmResolver.DotNet/EventDefinition.cs, src/AsmResolver.DotNet/PropertyDefinition.cs
Closes #168 
I named these 2 methods `ApplyMethods`. Do you prefer them to be named something different?
=> [Feature]: Add a SetSemanticMethods method to PropertyDefinition and EventDefinition

src/AsmResolver.DotNet/Code/Cil/CilMethodBody.cs, src/AsmResolver.DotNet/Config/Json/RuntimeConfiguration.cs, src/AsmResolver.DotNet/Config/Json/RuntimeConfigurationSerializerContext.cs, src/AsmResolver.DotNet/DynamicMethodDefinition.cs, src/AsmResolver.DotNet/DynamicMethodHelper.cs, src/AsmResolver.DotNet/RequiresUnreferencedCodeAttribute.cs, src/AsmResolver.PE.File/AsmResolver.PE.File.csproj, src/AsmResolver.PE.Win32Resources/AsmResolver.PE.Win32Resources.csproj, src/AsmResolver.PE/AsmResolver.PE.csproj, src/AsmResolver/AsmResolver.csproj, test/AsmResolver.PE.Tests/DotNet/Metadata/UserStringsStreamTest.cs
I was able to add trimming for:
* `AsmResolver`
* `AsmResolver.PE`
* `AsmResolver.PE.File`
* `AsmResolver.PE.Win32Resources`
I was not able to add trimming to `AsmResolver.DotNet`. Problems originated from only 3 files:
* `DynamicMethodHelper.cs`
* `ReferenceImporter.cs`
* `RuntimeConfiguration.cs`
Annotating these couple uses of json and reflection quickly devolved into me needing to annotate most of the library.
=> [Feature]: Allow .NET 6 assembly trimming for PE.File, PE and Win32Resources

src/AsmResolver.DotNet/Builder/Metadata/Blob/BlobStreamBuffer.cs, src/AsmResolver.DotNet/Code/Cil/CilMethodBodySerializer.cs, src/AsmResolver/IO/BinaryStreamWriter.cs, src/AsmResolver/IO/MemoryStreamWriterPool.cs, test/AsmResolver.Tests/IO/MemoryStreamReaderPoolTest.cs
Adds `MemoryStreamWriterPool` class that allows for renting `BinaryStreamWriter` instances from a pool. This significantly reduces the amount of allocated writer objects, as well as backing buffers when serializing code streams and blob signatures.
=> Rentable BinaryStreamWriters that write to temporary MemoryStream

src/AsmResolver.DotNet/Builder/DotNetDirectoryBuffer.MemberTree.cs, src/AsmResolver.DotNet/Builder/Metadata/Tables/DistinctMetadataTableBuffer.cs, src/AsmResolver.DotNet/Builder/Metadata/Tables/IMetadataTableBuffer.cs, src/AsmResolver.DotNet/Builder/Metadata/Tables/UnsortedMetadataTableBuffer.cs, src/AsmResolver.DotNet/Collections/MethodSemanticsCollection.cs, src/AsmResolver.DotNet/Serialized/SerializedGenericParameter.cs, src/AsmResolver.DotNet/Serialized/SerializedMethodDefinition.cs, src/AsmResolver.DotNet/Serialized/SerializedModuleDefinition.Metadata.cs, src/AsmResolver.DotNet/Serialized/SerializedModuleDefinition.cs, src/AsmResolver.DotNet/Serialized/SerializedPropertyDefinition.cs, src/AsmResolver.DotNet/Serialized/SerializedTypeDefinition.cs, src/AsmResolver.DotNet/Signatures/CustomAttributeSignature.cs, src/AsmResolver.DotNet/Signatures/GenericInstanceMethodSignature.cs, src/AsmResolver.DotNet/Signatures/MethodSignature.cs, src/AsmResolver.DotNet/Signatures/MethodSignatureBase.cs, src/AsmResolver.DotNet/Signatures/Types/ArrayTypeSignature.cs, src/AsmResolver.DotNet/Signatures/Types/FunctionPointerTypeSignature.cs, src/AsmResolver.DotNet/Signatures/Types/GenericInstanceTypeSignature.cs, src/AsmResolver.PE/DotNet/Metadata/Tables/MetadataTable.cs, src/AsmResolver/Collections/LazyList.cs, src/AsmResolver/Collections/OneToManyRelation.cs, src/AsmResolver/Collections/OneToOneRelation.cs, src/AsmResolver/Collections/OwnedCollection.cs, src/AsmResolver/Collections/RefList.cs, test/AsmResolver.Tests/Collections/RefListTest.cs
Includes:
- Add `RefList::Capacity.set`
- Add `IMetadataTableBuffer::EnsureCapacity(int)`
- Changes some internal `ModuleDefinition::GetXCollection` methods to return `ICollection<T>` instead of `IEnumerable<T>`.
- Use of `List.Capacity` in various reader and builder methods when the number of elements to add is known.
=> Add and use collection Capacity properties

src/AsmResolver.DotNet/Code/Cil/CilInstructionCollection.cs
The expanded instructions of Ldarga_S and Bge_Un_S are wrong.
=> Fix ExpandMacro.

src/AsmResolver.DotNet/Cloning/CallbackCloneListener.cs, src/AsmResolver.DotNet/Cloning/IMemberClonerListener.cs, src/AsmResolver.DotNet/Cloning/MemberCloner.Fields.cs, src/AsmResolver.DotNet/Cloning/MemberCloner.Methods.cs, src/AsmResolver.DotNet/Cloning/MemberCloner.Semantics.cs, src/AsmResolver.DotNet/Cloning/MemberCloner.cs, src/AsmResolver.DotNet/Cloning/MemberClonerListener.cs, test/AsmResolver.DotNet.Tests/Cloning/MetadataClonerTest.cs, test/AsmResolver.Tests/AsmResolver.Tests.csproj, test/AsmResolver.Tests/Listeners/CustomMemberClonerListener.cs
=> Callbacks implementation for MemberCloner

src/AsmResolver.DotNet/CustomAttribute.cs, src/AsmResolver.DotNet/Serialized/SerializedCustomAttribute.cs, src/AsmResolver.DotNet/Signatures/CustomAttributeSignature.cs, src/AsmResolver.DotNet/Signatures/SerializedCustomAttributeSignature.cs, test/AsmResolver.Benchmarks/ModuleReadWriteBenchmark.cs, test/AsmResolver.DotNet.Tests/CustomAttributeTest.cs, test/AsmResolver.DotNet.Tests/ModuleDefinitionTest.cs
Includes:
- `SerializedCustomAttributeSignature`, which is a lazy initialized version of `CustomAttributeSignature` that does not parse the arguments unless absolutely necessary.
- Adds convenience constructors to `CustomAttribute` and `CustomAttributeSignature`.
Closes #336
=> Lazy custom attribute signatures

src/AsmResolver.DotNet.Dynamic/DynamicMethodDefinition.cs, src/AsmResolver.DotNet.Dynamic/DynamicMethodHelper.cs, src/AsmResolver.DotNet/Code/Cil/CilMaxStackCalculator.cs, src/AsmResolver.DotNet/Code/Cil/CilMethodBody.cs, src/AsmResolver.DotNet/Code/Cil/CilMethodBodySerializer.cs, src/AsmResolver.DotNet/Code/Cil/CilOperandBuilder.cs, src/AsmResolver.DotNet/Code/Cil/OriginalMetadataTokenProvider.cs, src/AsmResolver.DotNet/Code/Native/NativeMethodBodySerializer.cs, src/AsmResolver.PE/DotNet/Cil/CilDisassembler.cs, test/AsmResolver.DotNet.Dynamic.Tests/DynamicMethodDefinitionTest.cs, test/AsmResolver.DotNet.Tests/Code/Cil/CilMethodBodyTest.cs
Includes:
- Individual components in a CIL body are now read (and error handled) separately.
- `CilMethodBody.FromReader` now uses the reader context's error listener to report parser errors.
- Bugfix: `CilMaxStackCalculator` now respects raw branch operand deltas.
- Bugfix: `CilOperandBuilder` now supports writing the raw string metadata tokens produced by `CilDisassembler` if it wasn't resolved before.
- Bugfix: `DynamicMethodDefinition` now correctly pulls code from underlying `DynamicILInfo` object if necessary.
- Add `OriginalMetadataTokenProvider` class.
=> Various CIL body parsing hardening improvements

src/AsmResolver.DotNet.Dynamic/DynamicCilOperandResolver.cs, src/AsmResolver.DotNet.Dynamic/DynamicMethodDefinition.cs, src/AsmResolver.DotNet/AssemblyReference.cs, src/AsmResolver.DotNet/ReferenceImporter.cs, test/AsmResolver.DotNet.Dynamic.Tests/DynamicMethodDefinitionTest.cs, test/AsmResolver.DotNet.Tests/ReferenceImporterTest.cs
=> BUGFIX: Import nested types by Reflection should retain declaring type and proper assembly fullname

src/AsmResolver.DotNet/AssemblyResolverBase.cs, src/AsmResolver.DotNet/DefaultMetadataResolver.cs, src/AsmResolver.DotNet/Signatures/SignatureComparer.ResolutionScope.cs, src/AsmResolver.DotNet/Signatures/SignatureComparer.cs, src/AsmResolver.DotNet/Signatures/SignatureComparisonFlags.cs
This pull request:
* Makes `SignatureComparer` immutable.
* Adds a new enum `SignatureComparisonFlags` for configuring `SignatureComparer`.
* Removes `IgnoreAssemblyVersionNumbers` and `AcceptNewerAssemblyVersionNumbers` from the public scope.
* Adds a static property for the `Default` instance of `SignatureComparer`.
=> SignatureComparer Improvements

src/AsmResolver/Collections/LazyList.cs
Ensures a modification to a `LazyList<T>` (and all its derivatives) is done atomically.
=> Guard lazylist methods with locks

src/AsmResolver.DotNet.Dynamic/DynamicMethodDefinition.cs, src/AsmResolver.DotNet.Dynamic/DynamicMethodHelper.cs, src/AsmResolver.DotNet.Dynamic/DynamicTypeSignatureReader.cs, src/AsmResolver.DotNet/Code/Cil/OriginalMetadataTokenProvider.cs, src/AsmResolver.DotNet/ReferenceImporter.cs, src/AsmResolver.DotNet/Signatures/BlobReadContext.cs, src/AsmResolver.DotNet/Signatures/Types/ITypeSignatureResolver.cs, src/AsmResolver.DotNet/Signatures/Types/PhysicalTypeSignatureResolver.cs, src/AsmResolver.DotNet/Signatures/Types/TypeSignature.cs, test/AsmResolver.DotNet.Dynamic.Tests/AsmResolver.DotNet.Dynamic.Tests.csproj, test/AsmResolver.DotNet.Dynamic.Tests/DynamicMethodDefinitionTest.cs, test/AsmResolver.DotNet.Tests/ReferenceImporterTest.cs, test/TestBinaries/DotNet/AsmResolver.DotNet.TestCases.Generics/GenericType.cs, test/TestBinaries/DotNet/AsmResolver.DotNet.TestCases.Generics/NonGenericType.cs
Transforms the dynamic method body reader to read as much from the underlying DynamicILInfo object as possible. Covers method bodies that are initialized via `SetCode` and `SetLocalSignature`. This PR does not include raw exception handler support.
=> Better DynamicILInfo support

src/AsmResolver.DotNet/Signatures/Marshal/LPArrayMarshalDescriptor.cs, test/AsmResolver.DotNet.Tests/AsmResolver.DotNet.Tests.csproj, test/AsmResolver.DotNet.Tests/Signatures/MarshalDescriptorTest.cs
Closes #378 
Reference: https://github.com/dotnet/runtime/blob/653be13516cea8317b4c307b31efba0bef8f1678/src/coreclr/vm/mlinfo.cpp#L550
=> BUGFIX: Make LPArrayMarshalDescriptor::ArrayElementType nullable.

docs/dotnet/managed-method-bodies.rst
[#Referencing members](https://asmresolver.readthedocs.io/en/development/dotnet/managed-method-bodies.html#referencing-members) has wrong instructions order (Console.WriteLine() without Ldstr when in Type[] it asks for string argument)
=> Fix docs order of instructions

src/AsmResolver.DotNet/Signatures/CustomAttributeNamedArgument.cs, src/AsmResolver.DotNet/Signatures/CustomAttributeSignature.cs, src/AsmResolver.DotNet/Signatures/Security/SecurityAttribute.cs, src/AsmResolver.DotNet/Signatures/SerializedCustomAttributeSignature.cs, test/AsmResolver.DotNet.Tests/CustomAttributeTest.cs, test/TestBinaries/DotNet/AsmResolver.DotNet.TestCases.CustomAttributes/AsmResolver.DotNet.TestCases.CustomAttributes.csproj, test/TestBinaries/DotNet/AsmResolver.DotNet.TestCases.CustomAttributes/CustomAttributesTestClass.cs, test/TestBinaries/DotNet/AsmResolver.DotNet.TestCases.CustomAttributes/TestCaseAttribute.Generic.cs
=> Support Generic Custom Attributes

src/AsmResolver.DotNet/Collections/Parameter.cs, src/AsmResolver.DotNet/Collections/ParameterCollection.cs, src/AsmResolver.DotNet/Signatures/MethodSignatureBase.cs, src/AsmResolver.DotNet/Signatures/Types/GenericParameterSignature.cs, test/AsmResolver.DotNet.Tests/Collections/ParameterCollectionTest.cs, test/TestBinaries/DotNet/AsmResolver.DotNet.TestCases.Methods/GenericInstanceMethods.cs
Changes:
* Added a new method to `Parameter` to make the creation of `ParameterDefinition` objects easier
* Don't use unbound generic types in virtual hidden this parameter.
* Fixed a bug that resulted in incorrect parameter count calculation for signatures with `ExplicitThis` flag set to true.
=> Add Parameter.CreateParameterDefinition helper method

docs/dotnet/bundles.rst, src/AsmResolver.DotNet/Bundles/BundleManifest.cs, src/AsmResolver.DotNet/Bundles/BundlerParameters.cs, test/AsmResolver.DotNet.Tests/Bundles/BundleManifestTest.cs
Introduces:
- `BundlerParameters::FromTemplate`
- `BundlerParameters::FromExistingBundle`
Deprecates:
- All constructors of `BundlerParameters`
Closes #420
=> Repackage AppHost files

docs/dotnet/type-signatures.rst, src/AsmResolver.DotNet/Signatures/Types/ArrayBaseTypeSignature.cs, src/AsmResolver.DotNet/Signatures/Types/ArrayTypeSignature.cs, src/AsmResolver.DotNet/Signatures/Types/ByReferenceTypeSignature.cs, src/AsmResolver.DotNet/Signatures/Types/CorLibTypeSignature.cs, src/AsmResolver.DotNet/Signatures/Types/CustomModifierTypeSignature.cs, src/AsmResolver.DotNet/Signatures/Types/FunctionPointerTypeSignature.cs, src/AsmResolver.DotNet/Signatures/Types/GenericInstanceTypeSignature.cs, src/AsmResolver.DotNet/Signatures/Types/PinnedTypeSignature.cs, src/AsmResolver.DotNet/Signatures/Types/PointerTypeSignature.cs, src/AsmResolver.DotNet/Signatures/Types/SzArrayTypeSignature.cs, src/AsmResolver.DotNet/Signatures/Types/TypeDefOrRefSignature.cs, src/AsmResolver.DotNet/Signatures/Types/TypeSignature.cs, src/AsmResolver.PE.File/Headers/OptionalHeader.cs, test/AsmResolver.DotNet.Tests/Signatures/TypeSignatureTest.cs, test/TestBinaries/DotNet/AsmResolver.DotNet.TestCases.Generics/GenericDerivedType.cs, test/TestBinaries/DotNet/AsmResolver.DotNet.TestCases.Generics/GenericInterfaceImplementation.cs, test/TestBinaries/DotNet/AsmResolver.DotNet.TestCases.Generics/IGenericInterface.cs, test/TestBinaries/DotNet/AsmResolver.DotNet.TestCases.Types/Int32Enum.cs, test/TestBinaries/DotNet/AsmResolver.DotNet.TestCases.Types/Int64Enum.cs
Implements the type compatibility and assignability rules as defined in ECMA-335 I.8.7
Introduces:
- `TypeSignature::GetUnderlyingType()`
- `TypeSignature::GetReducedType()`
- `TypeSignature::GetVerificationType()`
- `TypeSignature::GetIntermediateType()`
- `TypeSignature::GetDirectBaseClass()`
- `TypeSignature::GetDirectlyImplementedInterfaces()`
- `TypeSignature::StripModifiers()`
- `TypeSignature::IsCompatibleWith(TypeSignature)`
- `TypeSignature::IsAssignableTo(TypeSignature)`
- `ArrayBaseTypeSignature` base class for `ArrayTypeSignature` and `SzArrayTypeSignature`.
=> TypeSignature Compatibility and Assignability Rules

src/AsmResolver.DotNet/Signatures/SignatureComparer.ResolutionScope.cs, test/AsmResolver.DotNet.Tests/Bundles/BundleManifestTest.cs, test/AsmResolver.DotNet.Tests/Signatures/SignatureComparerTest.cs
=> Exclude AssemblyDescriptor::Version in hashcode computation when relaxing version comparisons

src/AsmResolver.DotNet/Memory/TypeMemoryLayoutDetector.cs, test/AsmResolver.DotNet.Tests/Memory/SequentialStructLayoutTest.cs, test/AsmResolver.DotNet.Tests/Memory/SequentialTestStructs.cs, test/AsmResolver.DotNet.Tests/Memory/StructLayoutTestBase.cs
=> Handle TypeSpecification in GetImpliedMemoryLayout

src/AsmResolver.DotNet/Code/Native/NativeSymbolsProvider.cs, test/AsmResolver.DotNet.Tests/Code/Native/NativeMethodBodyTest.cs
=> Allow for arbitrary symbols to be referenced in Native Method Bodies

docs/guides/dotnet/basics.md, src/AsmResolver.DotNet/DotNetRuntimeInfo.cs, src/AsmResolver.DotNet/KnownCorLibs.cs, src/AsmResolver.DotNet/ReflectionAssemblyDescriptor.cs, test/AsmResolver.DotNet.Tests/DotNetRuntimeInfoTest.cs
Includes:
- `DotNetRuntimeInfo::GetDefaultCorLib()`
- `KnownCorLibs::FromRuntimeInfo`
=> Get default CorLib reference from DotNetRuntimeInfo

docs/guides/dotnet/cloning.md, src/AsmResolver.DotNet/Cloning/AssignTokensClonerListener.cs, src/AsmResolver.DotNet/Cloning/MemberCloner.Fields.cs, src/AsmResolver.DotNet/Cloning/MemberCloner.Methods.cs, src/AsmResolver.DotNet/Cloning/MemberCloner.Semantics.cs, src/AsmResolver.DotNet/Cloning/MemberCloner.cs, src/AsmResolver.DotNet/Cloning/MemberClonerListenerList.cs, test/AsmResolver.DotNet.Tests/Cloning/MetadataClonerTest.cs
Includes
- `MemberClonerListenerList` for chaining multiple cloner listeners
- `AssignTokensClonerListener` for automatically assigning new tokens to cloned members.
- `MemberCloner::AddListener` for adding new listeners easily.
=> Multiple cloner listeners

src/AsmResolver.DotNet/Builder/DotNetDirectoryBuffer.TokenProvider.cs, src/AsmResolver.DotNet/Builder/DotNetDirectoryFactory.cs, src/AsmResolver.DotNet/Builder/TokenMapping.cs, src/AsmResolver/Collections/BitList.cs, test/AsmResolver.DotNet.Tests/Builder/TokenPreservation/TypeRefTokenPreservationTest.cs
Includes:
- Extra `BitList` bounds checks.
- Fix for token allocation within newly constructed modules.
- Relaxation of rules on duplicated members in metadata buffers.
=> Relax constraints on duplicated members in metadata buffers

docs/guides/dotnet/cloning.md, docs/guides/dotnet/managed-method-bodies.md, docs/guides/dotnet/member-tree.md, src/AsmResolver.DotNet/MethodDefinition.cs, src/AsmResolver.DotNet/TypeDefinition.cs, test/AsmResolver.DotNet.Tests/MethodDefinitionTest.cs, test/AsmResolver.DotNet.Tests/TypeDefinitionTest.cs, test/TestBinaries/DotNet/AsmResolver.DotNet.TestCases.Methods/Constructors.cs, test/TestBinaries/DotNet/AsmResolver.DotNet.TestCases.Methods/NoStaticConstructor.cs
Includes:
- Add `TypeDefinition::GetConstructor`
- Add overloads for `TypeDefinition::InheritsFrom` and `Implements` taking a namespace-name pair.
- Add `MethodDefinition::CreateConstructor` and `MethodDefinition::CreateStaticConstructor`.
- Expand docs on how to create and access metadata.
=> TypeDefinition::GetConstructor and others

src/AsmResolver.DotNet.Dynamic/AsmResolver.DotNet.Dynamic.csproj, src/AsmResolver.DotNet/AsmResolver.DotNet.csproj, src/AsmResolver.PE.File/AsmResolver.PE.File.csproj, src/AsmResolver.PE.Win32Resources/AsmResolver.PE.Win32Resources.csproj, src/AsmResolver.PE/AsmResolver.PE.csproj, src/AsmResolver.Symbols.Pdb/AsmResolver.Symbols.Pdb.csproj, src/AsmResolver/AsmResolver.csproj, src/AsmResolver/IO/BinaryStreamReader.cs, src/AsmResolver/IO/BinaryStreamWriter.cs, src/AsmResolver/IO/ByteArrayDataSource.cs, src/AsmResolver/IO/DataSourceExtensions.cs, src/AsmResolver/IO/DataSourceSlice.cs, src/AsmResolver/IO/DisplacedDataSource.cs, src/AsmResolver/IO/IBinaryStreamWriter.cs, src/AsmResolver/IO/ISpanBinaryStreamWriter.cs, src/AsmResolver/IO/ISpanDataSource.cs, src/AsmResolver/IO/MemoryMappedDataSource.cs, src/AsmResolver/IO/UnmanagedDataSource.cs, src/AsmResolver/IO/ZeroesDataSource.cs, src/AsmResolver/Utf8String.cs
This pull request adds basic support for `Span<T>` and `ReadOnlySpan<T>` to the `AsmResolver` and `AsmResolver.IO` namespaces.
Support is only implemented for .NET Standard 2.1 and higher, no attempt has been made to provide `Span<T>` support for .NET Standard 2.0 as it would introduce a dependency on `System.Memory`.
This PR also does not attempt to take advantage of this new support within the library. This is most likely better left to a separate PR (and/or set of issues).
The following new types are provided to avoid source and binary breaking changes in existing code:
```cs
namespace AsmResolver.IO
{
public interface ISpanDataSource : IDataSource
{
int ReadBytes(ulong address, Span<byte> buffer);
}
public interface ISpanBinaryStreamWriter : IBinaryStreamWriter
{
void …
```
=> Add basic Span<T> support

src/AsmResolver.DotNet/Cloning/CloneContextAwareReferenceImporter.cs, src/AsmResolver.DotNet/Cloning/MemberCloneContext.cs, src/AsmResolver.DotNet/Cloning/MemberCloner.cs, src/AsmResolver.DotNet/Signatures/Types/CorLibTypeFactory.cs, test/AsmResolver.DotNet.Tests/Cloning/MetadataClonerTest.cs, test/TestBinaries/DotNet/AsmResolver.DotNet.TestCases.CustomAttributes/CustomAttributesTestClass.cs
This solves an issue where imported type references point to cloned type definitions (e.g., in custom attribute arguments of type `System.Type`). 
Closes #482
=> Let MemberCloner keep track of included types by value

src/AsmResolver.DotNet/Signatures/SignatureComparer.TypeSignature.cs
Just fixing three instances of object.GetHashCode being called by mistake in `GenericInstanceTypeSignature` and `CustomModifierTypeSignature`. I had a few fields and methods in my assemblies where .Equals returned true (correctly) but .GetHashCode returned distinct hash codes.
=> Fix a couple of corner cases in SignatureComparer.GetHashCode

src/AsmResolver.DotNet/Collections/MemberCollection.cs, src/AsmResolver.DotNet/Collections/MethodSemanticsCollection.cs, src/AsmResolver.DotNet/ModuleDefinition.cs, src/AsmResolver.DotNet/Serialized/SerializedAssemblyDefinition.cs, src/AsmResolver.DotNet/Serialized/SerializedEventDefinition.cs, src/AsmResolver.DotNet/Serialized/SerializedGenericParameter.cs, src/AsmResolver.DotNet/Serialized/SerializedMethodDefinition.cs, src/AsmResolver.DotNet/Serialized/SerializedModuleDefinition.Metadata.cs, src/AsmResolver.DotNet/Serialized/SerializedModuleDefinition.cs, src/AsmResolver.DotNet/Serialized/SerializedPropertyDefinition.cs, src/AsmResolver.DotNet/Serialized/SerializedTypeDefinition.cs, src/AsmResolver.DotNet/Signatures/Types/CorLibTypeFactory.cs, src/AsmResolver/Collections/OwnedCollection.cs, test/AsmResolver.DotNet.Tests/FieldDefinitionTest.cs, test/AsmResolver.DotNet.Tests/TypeDefinitionTest.cs
Introduces internal `MemberCollection` to the metadata reader that can bypass owner checks when adding members. This should both fix a bug where members could be added to the exact same owner instance, and slightly improve performance as well when reading files.
=> BUGFIX: Prevent the same metadata members to be added twice to the exact same collection

src/AsmResolver.DotNet/Memory/MemoryLayoutAttributes.cs, src/AsmResolver.DotNet/Memory/TypeMemoryLayout.cs, src/AsmResolver.DotNet/Memory/TypeMemoryLayoutDetector.cs, test/AsmResolver.DotNet.Tests/Memory/MiscellaneousStructTest.cs
=> Add TypeMemoryLayout::IsReferenceOrContainsReferences.

docs/guides/peimage/win32resources.md, src/AsmResolver.PE.Win32Resources/IWin32Resource.cs, src/AsmResolver.PE.Win32Resources/Icon/IconResource.cs, src/AsmResolver.PE.Win32Resources/Version/VersionInfoResource.cs, src/AsmResolver.PE/Win32Resources/IResourceDirectory.cs, src/AsmResolver.PE/Win32Resources/ResourceDirectory.cs, test/AsmResolver.PE.Tests/Win32Resources/ResourceDirectoryTest.cs, test/AsmResolver.PE.Win32Resources.Tests/Icon/IconResourceTest.cs, test/AsmResolver.PE.Win32Resources.Tests/Version/VersionInfoResourceTest.cs
- Renames `ResourceDirectory::AddOrReplaceEntry` to `InsertOrReplaceEntry`
- Renames `IWin32Resource::AddToDirectory` to `InsertIntoDirectory`
Closes #532
=> Preserve resource entry order based on ID

src/AsmResolver.DotNet/EventDefinition.cs, src/AsmResolver.DotNet/PropertyDefinition.cs, test/AsmResolver.DotNet.Tests/PropertyDefinitionTest.cs
Should these set accessors modify `MethodDefinition.Semantics` too?
=> Set Accessors for Semantic Methods

src/AsmResolver.DotNet/TypeDescriptorExtensions.cs
The MemberReference constructor is already null forgiving. This just propagates it up.
=> Be more forgiving about null status of parameters given to CreateMemberReference

src/AsmResolver.PE/DotNet/Metadata/SerializedTableStream.cs
=> BUGFIX: Address off-by-one bounds check for table column sizes

src/AsmResolver/AsmResolver.csproj, src/AsmResolver/Shims/MemoryMappedFileShim.Unix.cs, src/AsmResolver/Shims/MemoryMappedFileShim.Windows.cs, src/AsmResolver/Shims/MemoryMappedFileShim.cs, src/AsmResolver/Shims/MemoryMappedFileShim.inbox.cs, src/Directory.Build.props
This PR makes the memory-mapped file shim implementation added in #544 to be used only when targeting .NET Framework 3.5. For all newer frameworks, the `MemoryMappedFileShim` class' implementation simply forwards to the inbox framework APIs.
We also multi-target to .NET Framework 4.6.2 (the earliest supported 4.x version) in order to avoid the shims where we can.
=> Use inbox memory-mapped file APIs where available.

src/AsmResolver.DotNet/Constant.cs, src/AsmResolver.DotNet/Signatures/DataBlobSignature.cs, test/AsmResolver.DotNet.Tests/ConstantTest.FromValue.cs, test/AsmResolver.DotNet.Tests/ConstantTest.cs, test/TestBinaries/DotNet/AsmResolver.DotNet.TestCases.Fields/Constants.cs
* Support null constants
* Add `DataBlobSignature::FromNull`
* Add `Constant::InterpretData`
* Add `Constant::FromNull`
* Add `Constant::FromDefault`
* Add `Constant::FromValue` overloads for `nint` and `nuint`
=> Constant Improvements

src/AsmResolver.DotNet/Builder/DotNetDirectoryBuffer.CodedIndices.cs, src/AsmResolver.DotNet/Builder/DotNetDirectoryBuffer.MemberTree.cs, src/AsmResolver.DotNet/Builder/DotNetDirectoryBuffer.TokenProvider.cs, src/AsmResolver.DotNet/Builder/DotNetDirectoryBuffer.cs, src/AsmResolver.DotNet/Builder/Metadata/BlobStreamBuffer.cs, src/AsmResolver.DotNet/Builder/Metadata/MemberNotImportedException.cs, src/AsmResolver.DotNet/Code/Cil/CilMethodBodySerializer.cs, src/AsmResolver.DotNet/Code/Cil/CilOperandBuilder.cs, src/AsmResolver.DotNet/Code/Cil/IMetadataTokenProvider.cs, src/AsmResolver.DotNet/Code/Cil/OriginalMetadataTokenProvider.cs, src/AsmResolver.DotNet/Signatures/BlobSerializationContext.cs, src/AsmResolver.DotNet/Signatures/ITypeCodedIndexProvider.cs, src/AsmResolver.DotNet/Signatures/SecurityAttribute.cs, src/AsmResolver.DotNet/Signatures/TypeSignature.cs
A common pitfall in building metadata is to reference metadata that is not imported yet. In such a case, `MemberNotImportedException` would be thrown during rebuild, with a message similar to the one below:
```
Member SomeNamespace.SomeType was not imported into the module.
```
However, while this explains the member that was left unimported, it does not describe which object referenced the unimported reference, making it hard to pinpoint where the error originated from.
This PR fills this gap by adding extra diagnostic tracking, containing the object that was responsible for the inclusion of this unimported reference. New error messages are now prefixed by this diagnostic source:
```
[In SomeNamespace.SomeType <Module>::SomeField]: Member SomeNamespace.SomeType was not imported into the …
```
=> Add DiagnosticSource to MemberNotImportedException

src/AsmResolver.DotNet/TypeDefinition.cs, test/AsmResolver.DotNet.Tests/TypeDefinitionTest.cs
`IsValueType` for `System.Enum` currently returns `true`. This PR changes it so it will return `false`. This fixes #635.
=> Make System.Enum a reference type. Fixes #635

src/AsmResolver.DotNet/DotNetCorePathProvider.cs, src/AsmResolver.DotNet/ModuleDefinition.cs, src/AsmResolver.DotNet/ReflectionHacks.cs, src/Directory.Build.props
This PR includes a few tweaks:
- Enable the AOT analyzer
- Fix all AOT warnings
=> Fix AOT warnings

src/AsmResolver.PE/DotNet/Metadata/Tables/EventAttributes.cs, test/AsmResolver.DotNet.Tests/EventDefinitionTest.cs
For consistency with `PropertyAttributes`. Also added a couple tests.
=> Add `EventAttributes.None`

src/AsmResolver.DotNet/ExportedType.cs
This PR adds a constructor overload for `ExportedType` to allow passing `Utf8String` values without round-tripping.
=> Add constructor overload for ExportedType

src/AsmResolver.DotNet/Code/Cil/CilExceptionHandler.cs, src/AsmResolver.DotNet/Code/Cil/CilMethodBody.cs, src/AsmResolver.DotNet/Code/Cil/CilMethodBodySerializer.cs, src/AsmResolver.DotNet/Code/Cil/SerializedCilMethodBody.cs, src/AsmResolver.PE/DotNet/Cil/FastCilReassembler.cs, test/AsmResolver.Benchmarks/ModuleReadWriteBenchmark.cs, test/AsmResolver.DotNet.Tests/Code/Cil/CilMethodBodyTest.cs, test/AsmResolver.PE.Tests/DotNet/Cil/FastCilReassemblerTest.cs, test/TestBinaries/DotNet/AsmResolver.DotNet.TestCases.Methods/MethodBodyTypes.cs
Currently, on .NET module build, AsmResolver always fully decodes all method bodies, including all instructions and exception handlers. However, many assembly processing workloads do not require editing every method body (if at all). For example, a symbol renamer does not ever touch any CIL instruction and only assignes new names to metadata. This results in a lot of wasted processing time and memory consumption, particularly on allocations of `CilInstruction` objects.
This PR addresses this by purposefully avoiding a full decoding of method bodies if they haven't been accessed by the user. The only thing we actually need to do to keep things consistent is patch any possible metadata tokens in a raw code stream or exception handler that may have changed after a rebuild.
- …
=> Avoid unnecessary decoding of instructions and exception handlers
