Washi1337/AsmResolver

src/AsmResolver.PE.File/Headers/DataDirectory.cs
src/AsmResolver.PE.File/Headers/SectionHeader.cs
src/AsmResolver.PE.File/PEFile.cs
src/AsmResolver.PE.File/PESection.cs

Pull request for v4

---

src/AsmResolver.DotNet/Code/Cil/CilMethodBody.cs
src/AsmResolver.DotNet/DynamicMethodDefinition.cs
src/AsmResolver.DotNet/DynamicMethodHelper.cs
src/AsmResolver.DotNet/FieldReader.cs
src/AsmResolver.DotNet/MethodDefinition.cs
src/AsmResolver.DotNet/Signatures/Types/TypeSignature.cs
src/AsmResolver/FieldReader.cs
test/AsmResolver.DotNet.Tests/Code/Cil/CilMethodBodyTest.cs
test/AsmResolver.DotNet.Tests/DynamicMethodDefinitionTest.cs
test/TestBinaries/DotNet/AsmResolver.DotNet.TestCases.Methods/AsmResolver.DotNet.TestCases.Methods.csproj
test/TestBinaries/DotNet/AsmResolver.DotNet.TestCases.Methods/TDynamicMethod.cs

Thanks, https://github.com/0xd4d for inspiring me to do this!
- This is something that I wanted to do for a side-project I was working on but adding it as a feature of AsmResolver seems the way to go :)

Implement DynamicMethodDefinition & CILMethodBody.FromDynamicMethod

---

src/AsmResolver.DotNet/MethodDefinition.cs

Add HasMethodBody property

---

src/AsmResolver.DotNet/Builder/DotNetDirectoryBuffer.MemberTree.cs
src/AsmResolver.DotNet/Builder/DotNetDirectoryBuffer.cs
src/AsmResolver.DotNet/FileReference.cs
test/AsmResolver.DotNet.Tests/ModuleDefinitionTest.cs

Bugfixes persistence exported types and file references

---

src/AsmResolver.PE/Debug/CodeView/CodeViewDataSegment.cs
src/AsmResolver.PE/Debug/CodeView/CodeViewSignature.cs
src/AsmResolver.PE/Debug/CodeView/RsdsDataSegment.cs
src/AsmResolver.PE/Debug/CodeViewDebugDataSegment.cs
src/AsmResolver.PE/Debug/DefaultDebugDataReader.cs

Add support for CodeView Debug Data

Add CodeView RSDS debug data parsing

---

src/AsmResolver.PE/Debug/CodeView/CodeViewDataSegment.cs
src/AsmResolver.PE/Debug/CodeView/CodeViewSignature.cs
src/AsmResolver.PE/Debug/CodeView/RsdsDataSegment.cs
src/AsmResolver.PE/Debug/DefaultDebugDataReader.cs
src/AsmResolver/IErrorListener.cs

Add error handling for corrupted rsds data
Minor code changes for consistency

Add missing NB debug data format signatures

---

src/AsmResolver.DotNet/Signatures/FieldSignature.cs
src/AsmResolver.DotNet/Signatures/MethodSignature.cs
src/AsmResolver.DotNet/Signatures/PropertySignature.cs
src/AsmResolver.DotNet/Signatures/Types/ArrayTypeSignature.cs
src/AsmResolver.DotNet/Signatures/Types/BoxedTypeSignature.cs
src/AsmResolver.DotNet/Signatures/Types/ByReferenceTypeSignature.cs
src/AsmResolver.DotNet/Signatures/Types/CorLibTypeSignature.cs
src/AsmResolver.DotNet/Signatures/Types/CustomModifierTypeSignature.cs
src/AsmResolver.DotNet/Signatures/Types/GenericInstanceTypeSignature.cs
src/AsmResolver.DotNet/Signatures/Types/GenericParameterSignature.cs
src/AsmResolver.DotNet/Signatures/Types/GenericTypeActivator.cs
src/AsmResolver.DotNet/Signatures/Types/ITypeSignatureVisitorState.cs
src/AsmResolver.DotNet/Signatures/Types/PinnedTypeSignature.cs
src/AsmResolver.DotNet/Signatures/Types/PointerTypeSignature.cs
src/AsmResolver.DotNet/Signatures/Types/SentinelTypeSignature.cs
src/AsmResolver.DotNet/Signatures/Types/SzArrayTypeSignature.cs
src/AsmResolver.DotNet/Signatures/Types/TypeDefOrRefSignature.cs
src/AsmResolver.DotNet/Signatures/Types/TypeSignature.cs

Feature that would allow us to write static visitor so we can avoid generating new visitor for each state

[WIP] Feature: State ITypeSignatureVisitor

---

src/AsmResolver.DotNet/Cloning/MemberCloner.Methods.cs
src/AsmResolver.DotNet/ModuleDefinition.cs

Fix cloning ldarg operand and XML documentation

---

src/AsmResolver.Workspaces/NullableAttributes.cs
src/AsmResolver.Workspaces/WorkspaceIndexNode.cs
test/AsmResolver.Workspaces.Tests/WorkspaceIndexNodeDataTest.cs

Allows us to set and get some data to WorkspaceNodeIndex

Workspace node data

---

Directory.Build.props
LICENSE.md
README.md
appveyor.yml
src/AsmResolver.DotNet/AsmResolver.DotNet.csproj
test/AsmResolver.DotNet.Tests/AsmResolver.DotNet.Tests.csproj

Move Xunit.SkippableFact to AsmResolver.DotNet.Tests project

---

src/AsmResolver.DotNet/PropertyDefinition.cs
src/AsmResolver.PE/DotNet/Metadata/Tables/Rows/PropertyAttributes.cs

AsmResolver was missing the `None` attribute and I had to use 0 instead.

Fix naming & xml docs and add PropertyAttributes.None

---

docs/dotnet/type-signatures.rst
src/AsmResolver.DotNet/Memory/TypeAlignmentDetector.cs
src/AsmResolver.DotNet/Memory/TypeMemoryLayoutDetector.cs
src/AsmResolver.DotNet/ReferenceImporter.cs
src/AsmResolver.DotNet/Signatures/Types/FunctionPointerTypeSignature.cs
src/AsmResolver.DotNet/Signatures/Types/GenericTypeActivator.cs
src/AsmResolver.DotNet/Signatures/Types/ITypeSignatureVisitor.cs
src/AsmResolver.DotNet/Signatures/Types/ITypeSignatureVisitorState.cs
src/AsmResolver.DotNet/Signatures/Types/Parsing/TypeNameBuilder.cs
src/AsmResolver.DotNet/Signatures/Types/TypeSignature.cs

Support FnPtr type signatures

---

src/AsmResolver.DotNet/Builder/DotNetDirectoryFactory.cs
src/AsmResolver.DotNet/TokenAllocator.cs
src/AsmResolver.PE/DotNet/Metadata/Tables/TableIndex.cs
test/AsmResolver.DotNet.Tests/TokenAllocatorTest.cs

Include manually assigned tokens in metadata building process

---

src/AsmResolver.PE.Win32Resources/AsmResolver.PE.Win32Resources.csproj
src/AsmResolver.PE.Win32Resources/Icon/IconEntry.cs
src/AsmResolver.PE.Win32Resources/Icon/IconGroupDirectory.cs
src/AsmResolver.PE.Win32Resources/Icon/IconGroupDirectoryEntry.cs
src/AsmResolver.PE.Win32Resources/Icon/IconResource.cs
src/AsmResolver.PE.Win32Resources/Version/FixedVersionInfo.cs
src/AsmResolver.PE.Win32Resources/Version/StringTable.cs
src/AsmResolver.PE.Win32Resources/Version/VersionInfoResource.cs
src/AsmResolver.PE.Win32Resources/Version/VersionTableEntry.cs
src/AsmResolver.PE.Win32Resources/Version/VersionTableEntryHeader.cs
test/AsmResolver.PE.Win32Resources.Tests/AsmResolver.PE.Win32Resources.Tests.csproj
test/AsmResolver.PE.Win32Resources.Tests/Icon/IconResourceTest.cs
test/AsmResolver.PE.Win32Resources.Tests/Version/VersionInfoResourceTest.cs

NRT Annotations for AsmResolver.Win32Resources

---

src/AsmResolver.DotNet/Code/Cil/CilInstructionExtensions.cs
src/AsmResolver.DotNet/Signatures/MethodSignatureBase.cs
test/AsmResolver.DotNet.Tests/AsmResolver.DotNet.Tests.csproj
test/AsmResolver.DotNet.Tests/Code/Cil/CilInstructionExtensionsTest.cs

[Opened another PR for the same issue, but based on the correct branch now :)](https://github.com/Washi1337/AsmResolver/pull/191#issuecomment-888282631)

Fix stack push/pop count when encountering a method with a modreq return type

---

src/AsmResolver.DotNet/Constant.cs
src/AsmResolver.DotNet/Signatures/DataBlobSignature.cs
test/AsmResolver.DotNet.Tests/ConstantTest.FromValue.cs
test/AsmResolver.DotNet.Tests/ConstantTest.cs
test/AsmResolver.DotNet.Tests/Signatures/DataBlobSignatureTest.cs

This pull request adds FromValue static methods to DataBlobSignature and Constant.

Feature/ FromValue methods for DataBlobSignature and Constant

---

.editorconfig
AsmResolver.sln

The editor config was set to LF, and all the files are CRLF, so I had to constantly fix my line endings before making commits.

[QOL]: Change line ending setting to CRLF

---

src/AsmResolver.DotNet/Collections/LazyRidListRelation.cs
src/AsmResolver.DotNet/Serialized/SerializedModuleDefinition.cs
src/AsmResolver.PE/DotNet/Metadata/Tables/TablesStream.cs

Fix Race Condition in LazyRidListRelation::EnsureIsInitialized and ::Initialize

---

docs/dotnet/importing.rst
src/AsmResolver.DotNet/AssemblyDescriptor.cs
src/AsmResolver.DotNet/ModuleDefinition.cs

Module Default Importer

---

docs/dotnet/dynamic-methods.rst
docs/dotnet/managed-method-bodies.rst
docs/dotnet/member-tree.rst
docs/index.rst
src/AsmResolver.DotNet.Dynamic/AsmResolver.DotNet.Dynamic.csproj
src/AsmResolver.DotNet/ModuleDefinition.cs

- Adds article on reading and using dynamic methods with AsmResolver
- Adds additional check in `ModuleDefinition::FromModule` for invalid base addresses.

Dynamic method documentation

---

src/AsmResolver.DotNet/TypeDefinition.cs
test/AsmResolver.DotNet.Tests/TypeDefinitionTest.cs

Add TypeDefinition.IsByRefLike

---

src/AsmResolver.DotNet/ModuleDefinition.cs
test/AsmResolver.DotNet.Tests/ModuleDefinitionTest.cs

Generic TryLookupMember overloads

---

docs/dotnet/advanced-pe-image-building.rst
src/AsmResolver.DotNet/Builder/DotNetDirectoryFactory.cs
src/AsmResolver.DotNet/Builder/MetadataBuilderFlags.cs
src/AsmResolver.DotNet/Serialized/ModuleReaderContext.cs
test/AsmResolver.DotNet.Tests/Builder/ManagedPEImageBuilderTest.cs

Metadata stream preservation

---

docs/index.rst
docs/pefile/sections.rst
docs/peimage/pe-building.rst
docs/segments.rst
src/AsmResolver.DotNet/Code/Native/NativeMethodBodySerializer.cs
src/AsmResolver.PE/Code/AddressFixup.cs
src/AsmResolver.PE/Code/AddressFixupExtensions.cs
src/AsmResolver.PE/Code/AddressFixupPatch.cs
src/AsmResolver.PE/Code/AddressFixupType.cs
src/AsmResolver.PE/Code/CodeSegment.cs
src/AsmResolver.PE/Platforms/Amd64Platform.cs
src/AsmResolver.PE/Platforms/I386Platform.cs
src/AsmResolver/IReadableSegment.cs
src/AsmResolver/ISegment.cs
src/AsmResolver/Patching/BytesPatch.cs
src/AsmResolver/Patching/IPatch.cs
src/AsmResolver/Patching/PatchContext.cs
src/AsmResolver/Patching/PatchedSegment.cs
test/AsmResolver.DotNet.Tests/Code/Native/NativeMethodBodyTest.cs
test/AsmResolver.PE.Tests/Code/AddressFixupTest.cs
test/AsmResolver.PE.Tests/DotNet/Builder/MixedModeAssemblyTest.cs
test/AsmResolver.Tests/Patching/PatchedSegmentTest.cs

- Implements #403.
- Obsoletes `CodeSegment`.

Fluent Patching API

---

src/AsmResolver.DotNet/Builder/DotNetDirectoryBuffer.CodedIndices.cs
src/AsmResolver.DotNet/Signatures/CustomAttributeSignature.cs
src/AsmResolver.DotNet/Signatures/SerializedCustomAttributeSignature.cs
test/AsmResolver.DotNet.Tests/CustomAttributeTest.cs

Add CA parameter count validation

---

src/AsmResolver.DotNet/AssemblyDefinition.cs
src/AsmResolver.DotNet/ModuleDefinition.cs
src/AsmResolver.DotNet/Serialized/SerializedModuleDefinition.cs
test/AsmResolver.DotNet.Tests/ModuleDefinitionTest.cs

Use working directory as a search directory for assembly resolution

---

Directory.Build.props
src/AsmResolver.DotNet.Dynamic/AsmResolver.DotNet.Dynamic.csproj
src/AsmResolver.DotNet/AsmResolver.DotNet.csproj
src/AsmResolver.PE.File/AsmResolver.PE.File.csproj
src/AsmResolver.PE.Win32Resources/AsmResolver.PE.Win32Resources.csproj
src/AsmResolver.PE/AsmResolver.PE.csproj
src/AsmResolver.Symbols.Pdb/AsmResolver.Symbols.Pdb.csproj
src/AsmResolver/AsmResolver.csproj

This pull request adds [source link](https://learn.microsoft.com/en-us/dotnet/standard/library-guidance/sourcelink) support to AsmResolver.

GitHub Source link

---

src/AsmResolver.DotNet/AsmResolver.DotNet.csproj
src/AsmResolver.DotNet/Config/Json/RuntimeConfiguration.cs
src/AsmResolver.DotNet/Config/Json/RuntimeConfigurationSerializerContext.cs
src/AsmResolver.DotNet/Config/Json/RuntimeFramework.cs
src/AsmResolver.DotNet/Config/Json/RuntimeOptions.cs
src/AsmResolver.DotNet/Config/Json/SimpleJson.cs
src/AsmResolver.DotNet/Signatures/DataBlobSignature.cs
test/AsmResolver.DotNet.Tests/Config/Json/RuntimeConfigurationTest.cs

Replace System.Text.Json with SimpleJSON for older build targets

---

.github/actions/setup-wine-ubuntu/action.yml
.github/workflows/reusable-build.yml

Downgraded wine-staging
Fixed version string escaping

Downgrade wine-staging

---

src/AsmResolver.PE.File/OptionalHeader.cs
src/AsmResolver.PE/Builder/UnmanagedPEFileBuilder.cs
src/AsmResolver.PE/Relocations/Builder/RelocationBlock.cs
src/AsmResolver.PE/Relocations/Builder/RelocationEntry.cs
test/AsmResolver.PE.Tests/Builder/UnmanagedPEFileBuilderTest.cs

UnmanagedPEFileBuilder: Do not duplicate exports and relocations

---

src/AsmResolver.DotNet/Signatures/SignatureComparer.MemberReferences.cs
src/AsmResolver.DotNet/Signatures/SignatureComparer.TypeSignature.cs
test/AsmResolver.DotNet.Tests/Signatures/SignatureComparerTest.cs
test/TestBinaries/DotNet/AsmResolver.DotNet.TestCases.Methods/GenericInstanceMethods.cs

SignatureComparer Symmetry

---

src/AsmResolver.DotNet/Cloning/MemberCloner.Semantics.cs
src/AsmResolver.DotNet/Cloning/MemberCloner.cs
test/AsmResolver.DotNet.Tests/Cloning/MetadataClonerTest.cs

BUGFIX: Include semantic member owners in ClonedMembers

---

src/AsmResolver.DotNet/Signatures/Parsing/TypeNameBuilder.cs
test/AsmResolver.DotNet.Tests/Signatures/TypeNameBuilderTest.cs

See: https://github.com/AssetRipper/AssetRipper/issues/1683

Fix Culture PublicKeyToken order

---

src/AsmResolver.DotNet.Dynamic/DynamicTypeSignatureReader.cs

.NET 7 has introduced the [`RuntimeTypeHandle.FromIntPtr`](https://learn.microsoft.com/en-us/dotnet/api/system.runtimetypehandle.fromintptr) API, and this PR uses it in `DynamicTypeSignatureReader` where available, instead of doing private reflection.

Use public API to get type from address where available.

---

src/AsmResolver.DotNet/ModuleDefinition.cs
test/AsmResolver.DotNet.Tests/ModuleDefinitionTest.cs

Fix CorLib module self-reference

---

docs/guides/dotnet/importing.md
src/AsmResolver.PE/Builder/ManagedPEFileBuilder.cs
src/AsmResolver.PE/Builder/PEFileBuilder.cs
src/AsmResolver.PE/Builder/UnmanagedPEFileBuilder.cs
test/AsmResolver.PE.Tests/Builder/ManagedPEFileBuilderTest.cs
test/TestBinaries/DotNet/AsmResolver.DotNet.TestCases.Fields/AsmResolver.DotNet.TestCases.Fields.csproj
test/TestBinaries/DotNet/AsmResolver.DotNet.TestCases.Fields/RVAField.cs

https://github.com/dotnet/runtime/blob/main/docs/design/specs/Ecma-335-Augments.md#rules-for-il-rewriters

Respect RVA field alignment requirements

---

src/AsmResolver.DotNet/AsmResolver.DotNet.csproj
src/AsmResolver.DotNet/Bundles/BundleAssemblyResolver.cs
src/AsmResolver.DotNet/DotNetCoreAssemblyResolver.cs
src/AsmResolver.DotNet/DotNetCorePathProvider.cs
src/AsmResolver.DotNet/DotNetFrameworkAssemblyResolver.cs
src/AsmResolver.DotNet/MonoPathProvider.cs
src/AsmResolver.DotNet/NativeMethods.cs
src/AsmResolver.DotNet/RuntimeContext.cs
test/AsmResolver.DotNet.Tests/AssemblyResolverTest.cs

- Add `MonoPathProvider`
- Let DotNetFrameworkAssemblyResolver try find Nix store mono paths
- Let DotNetCoreAssemblyResolver try find Nix store mono paths
- Simplify constructors of `DotNetCoreAssemblyResolver` and `DotNetCorePathProvider`

Add MonoPathProvider and add NixOS Path resolution

---

src/AsmResolver.DotNet/AssemblyResolverBase.cs

I'm assuming that this was the original intent, based on the comment that follows this block.

Fix failure to resolve assembly with culture
